spring.application.name=ticket-api

# Connect with PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_db
spring.datasource.username=postgres
spring.datasource.password=

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true