spring.application.name=ticket-api

# Connect with PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_db
spring.datasource.username=postgres
spring.datasource.password=

# Redis Configuration
spring.data.redis.database=0
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
